### PR TITLE
refactor: support `get_child_blocks` along with `get_child_descriptors`

### PR DESCRIPTION
**Pull request by Agrendalath**
**Description:** This method will be renamed in the Redwood release.

**Dependencies:** This is required to support changes from https://github.com/openedx/edx-platform/pull/31492.

**Testing instructions:** See that the tests from https://github.com/openedx/edx-platform/pull/31492 are passing.

**Reviewers:**
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [x] CI build is green
- [x] Version bumped
- [x] Changelog record added
- [x] Documentation updated (not only docstrings): n/a
- [x] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Agrendalath!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by ormsbee — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@Agrendalath 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/completion&entry.867055334=https://github.com/openedx/completion/pull/231&entry.1484655318=https://github.com/Agrendalath&entry.752974735=2023-04-25+16:29&entry.1917517419=2023-04-26+13:39&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by Agrendalath** [comment]
@ormsbee, would you mind creating a release to push the new version to PyPI?

**Comment by ormsbee** [comment]
@Agrendalath: Done (thanks to @kdmccormick, who clued me in to how we're using GitHub release now).

**Pull request merged**
