### PR TITLE
fix: Remove trailing comma that made catalog-info.yaml invalid yaml

### PR DESCRIPTION
**Pull request by pomegranited**
**Description:** Fix to the catalog-info.yaml file added by https://github.com/openedx/completion/pull/287

cf https://github.com/openedx/edx-submissions/pull/234

**Testing instructions:** N/A

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [x] Version bumped - N/A
- [x] Changelog record added - N/A
- [x] Documentation updated (not only docstrings) - N/A
- [x] Commits are squashed

**Post merge:**
- [x] Create a tag  - N/A
- [x] Check new version is pushed to PyPi after tag-triggered build is finished.  - N/A
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Review by sarina — APPROVED** [review]

**Comment by sarina** [comment]
@e0d still stuck 😢

**Comment by pomegranited** [comment]
@e0d @sarina This isn't the only PR on this repo experiencing this issue:

* https://github.com/openedx/completion/pull/290
* https://github.com/openedx/completion/pull/289

It works for https://github.com/openedx/completion/pull/279, but that PR was updated before I merged https://github.com/openedx/completion/pull/287 last week, which added catalog-info.yml.

I can't see how the cla checks work, but do they use Backstage at all? Is it possible that they're failing because of the typo this PR is trying to fix?

**Comment by sarina** [comment]
I pinged the team, so will hope to have an answer tomorrow. :\

**Comment by feanil** [comment]
@pomegranited CLA check sholud work correctly on other PRs now, you may need to add a comment or update the title to get it to run again.

**Pull request merged**
