### PR TITLE
fix: Remove trailing comma that caused catalog-in fo.yaml to be invalid yaml

### PR DESCRIPTION
**Pull request by pomegranited**
**Description:** Fix to the catalog-info.yaml file added by https://github.com/openedx/completion/pull/287

cf https://github.com/openedx/edx-submissions/pull/234

**Testing instructions:** N/A

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [x] Version bumped - N/A
- [x] Changelog record added - N/A
- [x] Documentation updated (not only docstrings) - N/A
- [x] Commits are squashed

**Post merge:**
- [x] Create a tag  - N/A
- [x] Check new version is pushed to PyPi after tag-triggered build is finished.  - N/A
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Review by sarina — APPROVED** [review]

**Comment by pomegranited** [comment]
Hi @mphilbrick211 could you have a look at why my cla check is failing here? I don't think anything has changed since this check succeeded last week? https://github.com/openedx/completion/pull/287

**Comment by sarina** [comment]
@pomegranited it doesn't look like the check is failing, it's just stalled, which I don't have a way to kick. Can you push an empty commit?

**Comment by pomegranited** [comment]
@sarina Tried re-pushing, but same effect.. and I'm not sure where that check is triggered from (it must be in the repo settings, not the .github/workflows?)

**Comment by e0d** [comment]
Commenting should rerun the cla check.

**Comment by sarina** [comment]
@e0d huh, that's weird... because Jill & I did comment to no avail. Anyway thanks for the magic comment 🪄 !

**Comment by e0d** [comment]
> @e0d huh, that's weird... because Jill & I did comment to no avail. Anyway thanks for the magic comment 🪄 !

I don't think my comment worked 😞 I think there's something weirdly stuck here. I'd try a new branch and PR.

**Comment by pomegranited** [comment]
Closed in favour of https://github.com/openedx/completion/pull/291

**Pull request closed without merging**
